export function mean(a){return a.length?a.reduce((x,y)=>x+y,0)/a.length:NaN}
export function median(a){if(!a.length)return NaN;const b=[...a].sort((x,y)=>x-y),m=b.length>>1;return b.length%2?b[m]:(b[m-1]+b[m])/2}
export function pearson(x,y){const n=Math.min(x.length,y.length);if(n<3)return NaN;const mx=mean(x),my=mean(y);let num=0,dx=0,dy=0;for(let i=0;i<n;i++){const a=x[i]-mx,b=y[i]-my;num+=a*b;dx+=a*a;dy+=b*b}return dx&&dy?num/Math.sqrt(dx*dy):NaN}
export function ranks(a){const z=a.map((v,i)=>({v,i})).sort((x,y)=>x.v-y.v),r=Array(a.length);for(let i=0;i<z.length;){let j=i+1;while(j<z.length&&z[j].v===z[i].v)j++;const q=(i+j-1)/2+1;for(let k=i;k<j;k++)r[z[k].i]=q;i=j}return r}
export function spearman(x,y){return pearson(ranks(x),ranks(y))}
function solve(A,b){const n=A.length,M=A.map((r,i)=>[...r,b[i]]);for(let k=0;k<n;k++){let p=k;for(let i=k+1;i<n;i++)if(Math.abs(M[i][k])>Math.abs(M[p][k]))p=i;[M[k],M[p]]=[M[p],M[k]];if(Math.abs(M[k][k])<1e-12)continue;const d=M[k][k];for(let j=k;j<=n;j++)M[k][j]/=d;for(let i=0;i<n;i++)if(i!==k){const q=M[i][k];for(let j=k;j<=n;j++)M[i][j]-=q*M[k][j]}}return M.map(r=>r[n])}
export function residuals(y,controls){const n=y.length,p=(controls[0]?.length||0)+1,X=Array.from({length:n},(_,i)=>[1,...(controls[i]||[])]),XtX=Array.from({length:p},()=>Array(p).fill(0)),Xty=Array(p).fill(0);for(let i=0;i<n;i++)for(let a=0;a<p;a++){Xty[a]+=X[i][a]*y[i];for(let b=0;b<p;b++)XtX[a][b]+=X[i][a]*X[i][b]}for(let i=0;i<p;i++)XtX[i][i]+=1e-10;const beta=solve(XtX,Xty);return y.map((v,i)=>v-X[i].reduce((s,q,j)=>s+q*beta[j],0))}
export function partialCorrelation(x,y,controls){return pearson(residuals(x,controls),residuals(y,controls))}
export function quantile(a,q){if(!a.length)return NaN;const b=[...a].sort((x,y)=>x-y),z=(b.length-1)*q,i=Math.floor(z),t=z-i;return b[i]*(1-t)+(b[i+1]??b[i])*t}
export function calibrationEdges(cells,key='berry'){const v=cells.map(c=>c[key]);return [quantile(v,.25),quantile(v,.5),quantile(v,.75)]}
export function applyCalibration(cells,edges,key='berry'){const groups=[[],[],[],[]];for(const c of cells){const v=c[key],i=v<=edges[0]?0:v<=edges[1]?1:v<=edges[2]?2:3;groups[i].push(c.error)}return groups.map((g,i)=>({band:i+1,n:g.length,median:median(g),mean:mean(g)}))}
export function findCounterexamples(cells){let near=null,reversal=null;for(let i=0;i<cells.length;i++)for(let j=i+1;j<cells.length;j++){const a=cells[i],b=cells[j],db=Math.abs(a.berry-b.berry),de=Math.abs(a.error-b.error);if(db<=.035&&(!near||de>near.de))near={a,b,db,de};const low=a.berry<b.berry?a:b,high=low===a?b:a;if(low.error>high.error+.035&&(!reversal||low.error-high.error>reversal.gap))reversal={low,high,gap:low.error-high.error}}return {near,reversal}}
